substitutions:
  board: esp32-s3-devkitc-1 
  variant: esp32s3
  name: esp32-s3-ervs
  friendly_name: ESP32 S3 ERVS
  project_name: "HA Voice and Sensor board"
  project_version: "1.0.0"
# Pin mapping for ERVS V0.2
  # bclk_pin: GPIO02 # WS
  # lrclk_pin: GPIO47 # CLK
  # din_pin: GPIO04  # DAT
  # mute_pin: GPIO16
  # i2s_dout_pin: GPIO10
  # bclk_pin2: GPIO37 # WS
  # lrclk_pin2: GPIO01 # CLK
  # mclk_pin: GPIO00
  # WS2812_pin: GPIO48 # LED Ring In Pin
  # i2c_sda: GPIO08
  # i2c_scl: GPIO09
  # uart_tx: GPIO43
  # uart_rx: GPIO44
  # uart_tx2: GPIO14
  # uart_rx2: GPIO13
  # out_pin_2410: GPIO46
  # cam_clk_pin: GPIO03
  # buz_pin: GPIO17
  # substitutions can't be used in camera_base, so this is only for reference
  # cam_d0: GPIO40    # Camera Data pin 0
  # cam_d1: GPIO42    # Camera Data pin 1
  # cam_d2: GPIO21    # Camera Data pin 2
  # cam_d3: GPIO41    # Camera Data pin 3
  # cam_d4: GPIO39    # Camera Data pin 4
  # cam_d5: GPIO12    # Camera Data pin 5
  # cam_d6: GPIO11    # Camera Data pin 6
  # cam_d7: GPIO18    # Camera Data pin 7
  # cam_vsync: GPIO07 # Camera VSYNC
  # cam_href: GPIO15  # Camera HREF
  # cam_pclk: GPIO38  # Camera Pixel Clock
  # cam_xclk: GPIO03  # Camera External Clock
  # i2c2_sda: GPIO05  # Camera SDA
  # i2c2_scl: GPIO06  # Camera SCL
  # cam_reset: GPIO36 # Camera Reset
  
# Pin mapping for ERVS V0.1
  bclk_pin: GPIO17 # WS
  lrclk_pin: GPIO47 # CLK
  din_pin: GPIO10  # DAT
  bclk_pin2: GPIO37 # WS
  lrclk_pin2: GPIO01 # CLK
  mclk_pin: GPIO0
  i2s_dout_pin: GPIO04
  WS2812_pin: GPIO48 # LED Ring In Pin
  i2c_sda: GPIO08
  i2c_scl: GPIO18
  uart_tx: GPIO44
  uart_rx: GPIO43
  uart_tx2: GPIO13
  uart_rx2: GPIO14
  out_pin_2410: GPIO12
  buz_pin: GPIO15

  hidden_ssid: "false"
  log_level: DEBUG

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2023.12.8
  name_add_mac_suffix: True

packages:
  device_base: !include include/ervs/esp32_base.yaml
  light_base: !include include/ervs/light_base.yaml
  ld2450_base: !include include/ervs/ld2450_base.yaml
  ld2410_base: !include include/ervs/ld2410_base.yaml
  # sgp40_base: !include include/sgp40_base.yaml
  # ov5640_base: !include include/ervs/camera_base.yaml
  bme680_base: !include include/ervs/bme680_base.yaml
  bh1750_base: !include include/ervs/bh1750_base.yaml
  voice_base: !include include/ervs/voice_base.yaml

logger:

debug:
  update_interval: 30s

api:
  encryption:
    key: "fOxYHKxYcSCSjVwbhLO9lEUZZVtAoszGIJVa4aiqVA4="

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - delay: 5s # Gives time for improv results to be transmitted
  #  - ble.disable:
  #on_disconnect:
  #  - ble.enable:
  ap:

ota:
  password: !secret wifi_password

i2c:
  sda: ${i2c_sda} #GPIO1
  scl: ${i2c_scl} #GPIO2
  scan: true
  frequency: 400kHz
  id: bus_a

time:
  - platform: sntp
    id: time_now